name: Wandering Palette
favicon: null
layout_spectrum: 0.16381331044249237
typography_spectrum: 0.5039494694210589
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.02498485380783677
  lightness: 0.5034922696650028
  saturation: 0.7333147460594773
  rhythmicContrast: 0.6616491116583347
purpose: []
